language: perl

install:
  - bash .travis-install-system.sh
  - cpanm --installdeps -n ./Acme-Alien-DontPanic

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - cd Acme-Alien-DontPanic
  - cpanm -v .
  - cd ..
  - cd Acme-Ford-Prefect
  - cpanm -v .

env:
  - ALIEN_FORCE=0 PATH=$PATH:$HOME/travislocal/bin LD_LIBRARY_PATH=$HOME/travislocal/lib PKG_CONFIG_PATH=$HOME/travislocal/lib/pkgconfig
  - ALIEN_FORCE=1

sudo: false
