language: perl

install:
  - cpanm -v Alien::Base
  - cd dontpanic
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - echo "/usr/local/lib" > local.conf
  - sudo cp local.conf /etc/ld.so.conf.d/local.conf
  - sudo ldconfig

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - cd Acme-Alien-DontPanic
  - cpanm -v .
  - cd ..
  - cd Acme-Ford-Prefect
  - cpanm -v .

env:
  - ALIEN_FORCE=1
  - ALIEN_FORCE=0
