language: perl

install:
  - cpanm -v Alien::Base
  - cd dontpanic
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - cd Acme-Alien-DontPanic
  - cpanm -v .
  - cd ../Acme-Ford-Prefect
  - cpanm -v .

env:
  - ALIEN_FORCE=1
  - ALIEN_FORCE=0
