---
abstract: 'Part of the test framework for Alien::Base'
author:
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test2::V0: '0'
configure_requires:
  Acme::Alien::DontPanic: '1.03'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Ford-Prefect
provides:
  Acme::Ford::Prefect:
    file: lib/Acme/Ford/Prefect.pm
    version: '1.03'
requires:
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#native
  MailingList: https://groups.google.com/forum/#!forum/perl5-alien
  bugtracker: http://github.com/Perl5-Alien/Acme-Ford-Prefect/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Perl5-Alien/Acme-Ford-Prefect
version: '1.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
